// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank.proto

package com.bok.bank.integration.grpc;

public interface AccountInfoRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:AccountInfoRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 accountId = 1;</code>
     *
     * @return The accountId.
     */
    long getAccountId();
}
