// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank.proto

package com.bok.bank.integration.grpc;

/**
 * Protobuf type {@code AccountCreationCheckRequest}
 */
public  final class AccountCreationCheckRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AccountCreationCheckRequest)
    AccountCreationCheckRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AccountCreationCheckRequest.newBuilder() to construct.
  private AccountCreationCheckRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AccountCreationCheckRequest() {
    fiscalCode_ = "";
    vatNumber_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AccountCreationCheckRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AccountCreationCheckRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            accountId_ = input.readUInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            fiscalCode_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            vatNumber_ = s;
            break;
          }
          case 32: {

            business_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bok.bank.integration.grpc.BankProto.internal_static_AccountCreationCheckRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bok.bank.integration.grpc.BankProto.internal_static_AccountCreationCheckRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bok.bank.integration.grpc.AccountCreationCheckRequest.class, com.bok.bank.integration.grpc.AccountCreationCheckRequest.Builder.class);
  }

  public static final int ACCOUNTID_FIELD_NUMBER = 1;
  private long accountId_;
  /**
   * <code>uint64 accountId = 1;</code>
   * @return The accountId.
   */
  public long getAccountId() {
    return accountId_;
  }

  public static final int FISCALCODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object fiscalCode_;
  /**
   * <code>string fiscalCode = 2;</code>
   * @return The fiscalCode.
   */
  public java.lang.String getFiscalCode() {
    java.lang.Object ref = fiscalCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fiscalCode_ = s;
      return s;
    }
  }
  /**
   * <code>string fiscalCode = 2;</code>
   * @return The bytes for fiscalCode.
   */
  public com.google.protobuf.ByteString
      getFiscalCodeBytes() {
    java.lang.Object ref = fiscalCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fiscalCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VATNUMBER_FIELD_NUMBER = 3;
  private volatile java.lang.Object vatNumber_;
  /**
   * <code>string vatNumber = 3;</code>
   * @return The vatNumber.
   */
  public java.lang.String getVatNumber() {
    java.lang.Object ref = vatNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      vatNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string vatNumber = 3;</code>
   * @return The bytes for vatNumber.
   */
  public com.google.protobuf.ByteString
      getVatNumberBytes() {
    java.lang.Object ref = vatNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      vatNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BUSINESS_FIELD_NUMBER = 4;
  private boolean business_;
  /**
   * <code>bool business = 4;</code>
   * @return The business.
   */
  public boolean getBusiness() {
    return business_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (accountId_ != 0L) {
      output.writeUInt64(1, accountId_);
    }
    if (!getFiscalCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fiscalCode_);
    }
    if (!getVatNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, vatNumber_);
    }
    if (business_ != false) {
      output.writeBool(4, business_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (accountId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, accountId_);
    }
    if (!getFiscalCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fiscalCode_);
    }
    if (!getVatNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, vatNumber_);
    }
    if (business_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, business_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bok.bank.integration.grpc.AccountCreationCheckRequest)) {
      return super.equals(obj);
    }
    com.bok.bank.integration.grpc.AccountCreationCheckRequest other = (com.bok.bank.integration.grpc.AccountCreationCheckRequest) obj;

    if (getAccountId()
        != other.getAccountId()) return false;
    if (!getFiscalCode()
        .equals(other.getFiscalCode())) return false;
    if (!getVatNumber()
        .equals(other.getVatNumber())) return false;
    if (getBusiness()
        != other.getBusiness()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACCOUNTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAccountId());
    hash = (37 * hash) + FISCALCODE_FIELD_NUMBER;
    hash = (53 * hash) + getFiscalCode().hashCode();
    hash = (37 * hash) + VATNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getVatNumber().hashCode();
    hash = (37 * hash) + BUSINESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBusiness());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bok.bank.integration.grpc.AccountCreationCheckRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bok.bank.integration.grpc.AccountCreationCheckRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bok.bank.integration.grpc.AccountCreationCheckRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bok.bank.integration.grpc.AccountCreationCheckRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bok.bank.integration.grpc.AccountCreationCheckRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bok.bank.integration.grpc.AccountCreationCheckRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bok.bank.integration.grpc.AccountCreationCheckRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bok.bank.integration.grpc.AccountCreationCheckRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bok.bank.integration.grpc.AccountCreationCheckRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bok.bank.integration.grpc.AccountCreationCheckRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bok.bank.integration.grpc.AccountCreationCheckRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bok.bank.integration.grpc.AccountCreationCheckRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bok.bank.integration.grpc.AccountCreationCheckRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AccountCreationCheckRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AccountCreationCheckRequest)
      com.bok.bank.integration.grpc.AccountCreationCheckRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bok.bank.integration.grpc.BankProto.internal_static_AccountCreationCheckRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bok.bank.integration.grpc.BankProto.internal_static_AccountCreationCheckRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bok.bank.integration.grpc.AccountCreationCheckRequest.class, com.bok.bank.integration.grpc.AccountCreationCheckRequest.Builder.class);
    }

    // Construct using com.bok.bank.integration.grpc.AccountCreationCheckRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      accountId_ = 0L;

      fiscalCode_ = "";

      vatNumber_ = "";

      business_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bok.bank.integration.grpc.BankProto.internal_static_AccountCreationCheckRequest_descriptor;
    }

    @java.lang.Override
    public com.bok.bank.integration.grpc.AccountCreationCheckRequest getDefaultInstanceForType() {
      return com.bok.bank.integration.grpc.AccountCreationCheckRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.bok.bank.integration.grpc.AccountCreationCheckRequest build() {
      com.bok.bank.integration.grpc.AccountCreationCheckRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bok.bank.integration.grpc.AccountCreationCheckRequest buildPartial() {
      com.bok.bank.integration.grpc.AccountCreationCheckRequest result = new com.bok.bank.integration.grpc.AccountCreationCheckRequest(this);
      result.accountId_ = accountId_;
      result.fiscalCode_ = fiscalCode_;
      result.vatNumber_ = vatNumber_;
      result.business_ = business_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bok.bank.integration.grpc.AccountCreationCheckRequest) {
        return mergeFrom((com.bok.bank.integration.grpc.AccountCreationCheckRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bok.bank.integration.grpc.AccountCreationCheckRequest other) {
      if (other == com.bok.bank.integration.grpc.AccountCreationCheckRequest.getDefaultInstance()) return this;
      if (other.getAccountId() != 0L) {
        setAccountId(other.getAccountId());
      }
      if (!other.getFiscalCode().isEmpty()) {
        fiscalCode_ = other.fiscalCode_;
        onChanged();
      }
      if (!other.getVatNumber().isEmpty()) {
        vatNumber_ = other.vatNumber_;
        onChanged();
      }
      if (other.getBusiness() != false) {
        setBusiness(other.getBusiness());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bok.bank.integration.grpc.AccountCreationCheckRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bok.bank.integration.grpc.AccountCreationCheckRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long accountId_ ;
    /**
     * <code>uint64 accountId = 1;</code>
     * @return The accountId.
     */
    public long getAccountId() {
      return accountId_;
    }
    /**
     * <code>uint64 accountId = 1;</code>
     * @param value The accountId to set.
     * @return This builder for chaining.
     */
    public Builder setAccountId(long value) {
      
      accountId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 accountId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccountId() {
      
      accountId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object fiscalCode_ = "";
    /**
     * <code>string fiscalCode = 2;</code>
     * @return The fiscalCode.
     */
    public java.lang.String getFiscalCode() {
      java.lang.Object ref = fiscalCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fiscalCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fiscalCode = 2;</code>
     * @return The bytes for fiscalCode.
     */
    public com.google.protobuf.ByteString
        getFiscalCodeBytes() {
      java.lang.Object ref = fiscalCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fiscalCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fiscalCode = 2;</code>
     * @param value The fiscalCode to set.
     * @return This builder for chaining.
     */
    public Builder setFiscalCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fiscalCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fiscalCode = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFiscalCode() {
      
      fiscalCode_ = getDefaultInstance().getFiscalCode();
      onChanged();
      return this;
    }
    /**
     * <code>string fiscalCode = 2;</code>
     * @param value The bytes for fiscalCode to set.
     * @return This builder for chaining.
     */
    public Builder setFiscalCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fiscalCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object vatNumber_ = "";
    /**
     * <code>string vatNumber = 3;</code>
     * @return The vatNumber.
     */
    public java.lang.String getVatNumber() {
      java.lang.Object ref = vatNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vatNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string vatNumber = 3;</code>
     * @return The bytes for vatNumber.
     */
    public com.google.protobuf.ByteString
        getVatNumberBytes() {
      java.lang.Object ref = vatNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vatNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string vatNumber = 3;</code>
     * @param value The vatNumber to set.
     * @return This builder for chaining.
     */
    public Builder setVatNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      vatNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string vatNumber = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearVatNumber() {
      
      vatNumber_ = getDefaultInstance().getVatNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string vatNumber = 3;</code>
     * @param value The bytes for vatNumber to set.
     * @return This builder for chaining.
     */
    public Builder setVatNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      vatNumber_ = value;
      onChanged();
      return this;
    }

    private boolean business_ ;
    /**
     * <code>bool business = 4;</code>
     * @return The business.
     */
    public boolean getBusiness() {
      return business_;
    }
    /**
     * <code>bool business = 4;</code>
     * @param value The business to set.
     * @return This builder for chaining.
     */
    public Builder setBusiness(boolean value) {
      
      business_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool business = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBusiness() {
      
      business_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AccountCreationCheckRequest)
  }

  // @@protoc_insertion_point(class_scope:AccountCreationCheckRequest)
  private static final com.bok.bank.integration.grpc.AccountCreationCheckRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bok.bank.integration.grpc.AccountCreationCheckRequest();
  }

  public static com.bok.bank.integration.grpc.AccountCreationCheckRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AccountCreationCheckRequest>
      PARSER = new com.google.protobuf.AbstractParser<AccountCreationCheckRequest>() {
    @java.lang.Override
    public AccountCreationCheckRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AccountCreationCheckRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AccountCreationCheckRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AccountCreationCheckRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bok.bank.integration.grpc.AccountCreationCheckRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

