// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank.proto

package com.bok.bank.integration.grpc;

public interface AccountCreationCheckResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:AccountCreationCheckResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool permitted = 1;</code>
     *
     * @return The permitted.
     */
    boolean getPermitted();
}
