// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank.proto

package com.bok.bank.integration.grpc;

public interface AccountCreationCheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AccountCreationCheckRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 accountId = 1;</code>
   * @return The accountId.
   */
  long getAccountId();

  /**
   * <code>string fiscalCode = 2;</code>
   * @return The fiscalCode.
   */
  java.lang.String getFiscalCode();
  /**
   * <code>string fiscalCode = 2;</code>
   * @return The bytes for fiscalCode.
   */
  com.google.protobuf.ByteString
      getFiscalCodeBytes();

  /**
   * <code>string vatNumber = 3;</code>
   * @return The vatNumber.
   */
  java.lang.String getVatNumber();
  /**
   * <code>string vatNumber = 3;</code>
   * @return The bytes for vatNumber.
   */
  com.google.protobuf.ByteString
      getVatNumberBytes();

  /**
   * <code>bool business = 4;</code>
   * @return The business.
   */
  boolean getBusiness();
}
