// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank.proto

package com.bok.bank.integration.grpc;

public interface AccountInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AccountInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string middleName = 2;</code>
   * @return The middleName.
   */
  java.lang.String getMiddleName();
  /**
   * <code>string middleName = 2;</code>
   * @return The bytes for middleName.
   */
  com.google.protobuf.ByteString
      getMiddleNameBytes();

  /**
   * <code>string surname = 3;</code>
   * @return The surname.
   */
  java.lang.String getSurname();
  /**
   * <code>string surname = 3;</code>
   * @return The bytes for surname.
   */
  com.google.protobuf.ByteString
      getSurnameBytes();

  /**
   * <code>string email = 4;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 4;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
