// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank.proto

package com.bok.bank.integration.grpc;

public interface AuthorizationRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:AuthorizationRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 accountId = 1;</code>
     *
     * @return The accountId.
     */
    long getAccountId();

    /**
     * <code>string extTransactionId = 2;</code>
     *
     * @return The extTransactionId.
     */
    java.lang.String getExtTransactionId();

    /**
     * <code>string extTransactionId = 2;</code>
     *
     * @return The bytes for extTransactionId.
     */
    com.google.protobuf.ByteString
    getExtTransactionIdBytes();

    /**
     * <code>.Money money = 3;</code>
     *
     * @return Whether the money field is set.
     */
    boolean hasMoney();

    /**
     * <code>.Money money = 3;</code>
     *
     * @return The money.
     */
    com.bok.bank.integration.grpc.Money getMoney();

    /**
     * <code>.Money money = 3;</code>
     */
    com.bok.bank.integration.grpc.MoneyOrBuilder getMoneyOrBuilder();

    /**
     * <code>string fromMarket = 4;</code>
     *
     * @return The fromMarket.
     */
    java.lang.String getFromMarket();

    /**
     * <code>string fromMarket = 4;</code>
     *
     * @return The bytes for fromMarket.
     */
    com.google.protobuf.ByteString
    getFromMarketBytes();
}
