// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank.proto

package com.bok.bank.integration.grpc;

public interface AuthorizationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AuthorizationResponse)
    com.google.protobuf.MessageOrBuilder {
}
