// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank.proto

package com.bok.bank.integration.grpc;

/**
 * Protobuf type {@code AuthorizationRequest}
 */
public  final class AuthorizationRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AuthorizationRequest)
    AuthorizationRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AuthorizationRequest.newBuilder() to construct.
  private AuthorizationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AuthorizationRequest() {
    extTransactionId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AuthorizationRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AuthorizationRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            accountId_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            extTransactionId_ = s;
            break;
          }
          case 26: {
            com.bok.bank.integration.grpc.Money.Builder subBuilder = null;
            if (money_ != null) {
              subBuilder = money_.toBuilder();
            }
            money_ = input.readMessage(com.bok.bank.integration.grpc.Money.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(money_);
              money_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bok.bank.integration.grpc.BankProto.internal_static_AuthorizationRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bok.bank.integration.grpc.BankProto.internal_static_AuthorizationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bok.bank.integration.grpc.AuthorizationRequest.class, com.bok.bank.integration.grpc.AuthorizationRequest.Builder.class);
  }

  public static final int ACCOUNTID_FIELD_NUMBER = 1;
  private long accountId_;
  /**
   * <code>int64 accountId = 1;</code>
   * @return The accountId.
   */
  public long getAccountId() {
    return accountId_;
  }

  public static final int EXTTRANSACTIONID_FIELD_NUMBER = 2;
  private volatile java.lang.Object extTransactionId_;
  /**
   * <code>string extTransactionId = 2;</code>
   * @return The extTransactionId.
   */
  public java.lang.String getExtTransactionId() {
    java.lang.Object ref = extTransactionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      extTransactionId_ = s;
      return s;
    }
  }
  /**
   * <code>string extTransactionId = 2;</code>
   * @return The bytes for extTransactionId.
   */
  public com.google.protobuf.ByteString
      getExtTransactionIdBytes() {
    java.lang.Object ref = extTransactionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      extTransactionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MONEY_FIELD_NUMBER = 3;
  private com.bok.bank.integration.grpc.Money money_;
  /**
   * <code>.Money money = 3;</code>
   * @return Whether the money field is set.
   */
  public boolean hasMoney() {
    return money_ != null;
  }
  /**
   * <code>.Money money = 3;</code>
   * @return The money.
   */
  public com.bok.bank.integration.grpc.Money getMoney() {
    return money_ == null ? com.bok.bank.integration.grpc.Money.getDefaultInstance() : money_;
  }
  /**
   * <code>.Money money = 3;</code>
   */
  public com.bok.bank.integration.grpc.MoneyOrBuilder getMoneyOrBuilder() {
    return getMoney();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (accountId_ != 0L) {
      output.writeInt64(1, accountId_);
    }
    if (!getExtTransactionIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, extTransactionId_);
    }
    if (money_ != null) {
      output.writeMessage(3, getMoney());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (accountId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, accountId_);
    }
    if (!getExtTransactionIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, extTransactionId_);
    }
    if (money_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getMoney());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bok.bank.integration.grpc.AuthorizationRequest)) {
      return super.equals(obj);
    }
    com.bok.bank.integration.grpc.AuthorizationRequest other = (com.bok.bank.integration.grpc.AuthorizationRequest) obj;

    if (getAccountId()
        != other.getAccountId()) return false;
    if (!getExtTransactionId()
        .equals(other.getExtTransactionId())) return false;
    if (hasMoney() != other.hasMoney()) return false;
    if (hasMoney()) {
      if (!getMoney()
          .equals(other.getMoney())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACCOUNTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAccountId());
    hash = (37 * hash) + EXTTRANSACTIONID_FIELD_NUMBER;
    hash = (53 * hash) + getExtTransactionId().hashCode();
    if (hasMoney()) {
      hash = (37 * hash) + MONEY_FIELD_NUMBER;
      hash = (53 * hash) + getMoney().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bok.bank.integration.grpc.AuthorizationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bok.bank.integration.grpc.AuthorizationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bok.bank.integration.grpc.AuthorizationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bok.bank.integration.grpc.AuthorizationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bok.bank.integration.grpc.AuthorizationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bok.bank.integration.grpc.AuthorizationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bok.bank.integration.grpc.AuthorizationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bok.bank.integration.grpc.AuthorizationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bok.bank.integration.grpc.AuthorizationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bok.bank.integration.grpc.AuthorizationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bok.bank.integration.grpc.AuthorizationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bok.bank.integration.grpc.AuthorizationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bok.bank.integration.grpc.AuthorizationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AuthorizationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AuthorizationRequest)
      com.bok.bank.integration.grpc.AuthorizationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bok.bank.integration.grpc.BankProto.internal_static_AuthorizationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bok.bank.integration.grpc.BankProto.internal_static_AuthorizationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bok.bank.integration.grpc.AuthorizationRequest.class, com.bok.bank.integration.grpc.AuthorizationRequest.Builder.class);
    }

    // Construct using com.bok.bank.integration.grpc.AuthorizationRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      accountId_ = 0L;

      extTransactionId_ = "";

      if (moneyBuilder_ == null) {
        money_ = null;
      } else {
        money_ = null;
        moneyBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bok.bank.integration.grpc.BankProto.internal_static_AuthorizationRequest_descriptor;
    }

    @java.lang.Override
    public com.bok.bank.integration.grpc.AuthorizationRequest getDefaultInstanceForType() {
      return com.bok.bank.integration.grpc.AuthorizationRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.bok.bank.integration.grpc.AuthorizationRequest build() {
      com.bok.bank.integration.grpc.AuthorizationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bok.bank.integration.grpc.AuthorizationRequest buildPartial() {
      com.bok.bank.integration.grpc.AuthorizationRequest result = new com.bok.bank.integration.grpc.AuthorizationRequest(this);
      result.accountId_ = accountId_;
      result.extTransactionId_ = extTransactionId_;
      if (moneyBuilder_ == null) {
        result.money_ = money_;
      } else {
        result.money_ = moneyBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bok.bank.integration.grpc.AuthorizationRequest) {
        return mergeFrom((com.bok.bank.integration.grpc.AuthorizationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bok.bank.integration.grpc.AuthorizationRequest other) {
      if (other == com.bok.bank.integration.grpc.AuthorizationRequest.getDefaultInstance()) return this;
      if (other.getAccountId() != 0L) {
        setAccountId(other.getAccountId());
      }
      if (!other.getExtTransactionId().isEmpty()) {
        extTransactionId_ = other.extTransactionId_;
        onChanged();
      }
      if (other.hasMoney()) {
        mergeMoney(other.getMoney());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bok.bank.integration.grpc.AuthorizationRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bok.bank.integration.grpc.AuthorizationRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long accountId_ ;
    /**
     * <code>int64 accountId = 1;</code>
     * @return The accountId.
     */
    public long getAccountId() {
      return accountId_;
    }
    /**
     * <code>int64 accountId = 1;</code>
     * @param value The accountId to set.
     * @return This builder for chaining.
     */
    public Builder setAccountId(long value) {
      
      accountId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 accountId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccountId() {
      
      accountId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object extTransactionId_ = "";
    /**
     * <code>string extTransactionId = 2;</code>
     * @return The extTransactionId.
     */
    public java.lang.String getExtTransactionId() {
      java.lang.Object ref = extTransactionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extTransactionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string extTransactionId = 2;</code>
     * @return The bytes for extTransactionId.
     */
    public com.google.protobuf.ByteString
        getExtTransactionIdBytes() {
      java.lang.Object ref = extTransactionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extTransactionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string extTransactionId = 2;</code>
     * @param value The extTransactionId to set.
     * @return This builder for chaining.
     */
    public Builder setExtTransactionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      extTransactionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string extTransactionId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearExtTransactionId() {
      
      extTransactionId_ = getDefaultInstance().getExtTransactionId();
      onChanged();
      return this;
    }
    /**
     * <code>string extTransactionId = 2;</code>
     * @param value The bytes for extTransactionId to set.
     * @return This builder for chaining.
     */
    public Builder setExtTransactionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      extTransactionId_ = value;
      onChanged();
      return this;
    }

    private com.bok.bank.integration.grpc.Money money_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bok.bank.integration.grpc.Money, com.bok.bank.integration.grpc.Money.Builder, com.bok.bank.integration.grpc.MoneyOrBuilder> moneyBuilder_;
    /**
     * <code>.Money money = 3;</code>
     * @return Whether the money field is set.
     */
    public boolean hasMoney() {
      return moneyBuilder_ != null || money_ != null;
    }
    /**
     * <code>.Money money = 3;</code>
     * @return The money.
     */
    public com.bok.bank.integration.grpc.Money getMoney() {
      if (moneyBuilder_ == null) {
        return money_ == null ? com.bok.bank.integration.grpc.Money.getDefaultInstance() : money_;
      } else {
        return moneyBuilder_.getMessage();
      }
    }
    /**
     * <code>.Money money = 3;</code>
     */
    public Builder setMoney(com.bok.bank.integration.grpc.Money value) {
      if (moneyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        money_ = value;
        onChanged();
      } else {
        moneyBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Money money = 3;</code>
     */
    public Builder setMoney(
        com.bok.bank.integration.grpc.Money.Builder builderForValue) {
      if (moneyBuilder_ == null) {
        money_ = builderForValue.build();
        onChanged();
      } else {
        moneyBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Money money = 3;</code>
     */
    public Builder mergeMoney(com.bok.bank.integration.grpc.Money value) {
      if (moneyBuilder_ == null) {
        if (money_ != null) {
          money_ =
            com.bok.bank.integration.grpc.Money.newBuilder(money_).mergeFrom(value).buildPartial();
        } else {
          money_ = value;
        }
        onChanged();
      } else {
        moneyBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Money money = 3;</code>
     */
    public Builder clearMoney() {
      if (moneyBuilder_ == null) {
        money_ = null;
        onChanged();
      } else {
        money_ = null;
        moneyBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Money money = 3;</code>
     */
    public com.bok.bank.integration.grpc.Money.Builder getMoneyBuilder() {
      
      onChanged();
      return getMoneyFieldBuilder().getBuilder();
    }
    /**
     * <code>.Money money = 3;</code>
     */
    public com.bok.bank.integration.grpc.MoneyOrBuilder getMoneyOrBuilder() {
      if (moneyBuilder_ != null) {
        return moneyBuilder_.getMessageOrBuilder();
      } else {
        return money_ == null ?
            com.bok.bank.integration.grpc.Money.getDefaultInstance() : money_;
      }
    }
    /**
     * <code>.Money money = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bok.bank.integration.grpc.Money, com.bok.bank.integration.grpc.Money.Builder, com.bok.bank.integration.grpc.MoneyOrBuilder> 
        getMoneyFieldBuilder() {
      if (moneyBuilder_ == null) {
        moneyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.bok.bank.integration.grpc.Money, com.bok.bank.integration.grpc.Money.Builder, com.bok.bank.integration.grpc.MoneyOrBuilder>(
                getMoney(),
                getParentForChildren(),
                isClean());
        money_ = null;
      }
      return moneyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AuthorizationRequest)
  }

  // @@protoc_insertion_point(class_scope:AuthorizationRequest)
  private static final com.bok.bank.integration.grpc.AuthorizationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bok.bank.integration.grpc.AuthorizationRequest();
  }

  public static com.bok.bank.integration.grpc.AuthorizationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AuthorizationRequest>
      PARSER = new com.google.protobuf.AbstractParser<AuthorizationRequest>() {
    @java.lang.Override
    public AuthorizationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AuthorizationRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AuthorizationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AuthorizationRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bok.bank.integration.grpc.AuthorizationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

