// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank.proto

package com.bok.bank.integration.grpc;

public final class BankProto {
  private BankProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AccountInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AccountInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AccountInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AccountInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AccountCreationCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AccountCreationCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AccountCreationCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AccountCreationCheckResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthorizationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthorizationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthorizationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthorizationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Money_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Money_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbank.proto\"\'\n\022AccountInfoRequest\022\021\n\tac" +
      "countId\030\001 \001(\004\"W\n\023AccountInfoResponse\022\014\n\004" +
      "name\030\001 \001(\t\022\022\n\nmiddleName\030\002 \001(\t\022\017\n\007surnam" +
      "e\030\003 \001(\t\022\r\n\005email\030\004 \001(\t\"i\n\033AccountCreatio" +
      "nCheckRequest\022\021\n\taccountId\030\001 \001(\004\022\022\n\nfisc" +
      "alCode\030\002 \001(\t\022\021\n\tvatNumber\030\003 \001(\t\022\020\n\010busin" +
      "ess\030\004 \001(\010\"1\n\034AccountCreationCheckRespons" +
      "e\022\021\n\tpermitted\030\001 \001(\010\"n\n\024AuthorizationReq" +
      "uest\022\021\n\taccountId\030\001 \001(\003\022\030\n\020extTransactio" +
      "nId\030\002 \001(\t\022\025\n\005money\030\003 \001(\0132\006.Money\022\022\n\nfrom" +
      "Market\030\004 \001(\t\"D\n\025AuthorizationResponse\022\022\n" +
      "\nauthorized\030\001 \001(\010\022\027\n\017authorizationId\030\002 \001" +
      "(\t\"4\n\005Money\022\033\n\010currency\030\001 \001(\0162\t.Currency" +
      "\022\016\n\006amount\030\002 \001(\001*%\n\010Currency\022\007\n\003USD\020\000\022\007\n" +
      "\003EUR\020\001\022\007\n\003AUD\020\0022\324\001\n\004Bank\022:\n\tAuthorize\022\025." +
      "AuthorizationRequest\032\026.AuthorizationResp" +
      "onse\022;\n\016GetAccountInfo\022\023.AccountInfoRequ" +
      "est\032\024.AccountInfoResponse\022S\n\024AccountCrea" +
      "tionCheck\022\034.AccountCreationCheckRequest\032" +
      "\035.AccountCreationCheckResponseB,\n\035com.bo" +
      "k.bank.integration.grpcB\tBankProtoP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AccountInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AccountInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AccountInfoRequest_descriptor,
        new java.lang.String[] { "AccountId", });
    internal_static_AccountInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AccountInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AccountInfoResponse_descriptor,
        new java.lang.String[] { "Name", "MiddleName", "Surname", "Email", });
    internal_static_AccountCreationCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AccountCreationCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AccountCreationCheckRequest_descriptor,
        new java.lang.String[] { "AccountId", "FiscalCode", "VatNumber", "Business", });
    internal_static_AccountCreationCheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AccountCreationCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AccountCreationCheckResponse_descriptor,
        new java.lang.String[] { "Permitted", });
    internal_static_AuthorizationRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_AuthorizationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthorizationRequest_descriptor,
        new java.lang.String[] { "AccountId", "ExtTransactionId", "Money", "FromMarket", });
    internal_static_AuthorizationResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_AuthorizationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthorizationResponse_descriptor,
        new java.lang.String[] { "Authorized", "AuthorizationId", });
    internal_static_Money_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Money_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Money_descriptor,
        new java.lang.String[] { "Currency", "Amount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
