// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank.proto

package com.bok.bank.integration.grpc;

/**
 * Protobuf enum {@code Currency}
 */
public enum Currency
        implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>USD = 0;</code>
     */
    USD(0),
    /**
     * <code>EUR = 1;</code>
     */
    EUR(1),
    /**
     * <code>AUD = 2;</code>
     */
    AUD(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>USD = 0;</code>
     */
    public static final int USD_VALUE = 0;
    /**
     * <code>EUR = 1;</code>
     */
    public static final int EUR_VALUE = 1;
    /**
     * <code>AUD = 2;</code>
     */
    public static final int AUD_VALUE = 2;
    private static final com.google.protobuf.Internal.EnumLiteMap<
            Currency> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Currency>() {
                public Currency findValueByNumber(int number) {
                    return Currency.forNumber(number);
                }
            };
    private static final Currency[] VALUES = values();
    private final int value;

    private Currency(int value) {
        this.value = value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Currency valueOf(int value) {
        return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Currency forNumber(int value) {
        switch (value) {
            case 0:
                return USD;
            case 1:
                return EUR;
            case 2:
                return AUD;
            default:
                return null;
        }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Currency>
    internalGetValueMap() {
        return internalValueMap;
    }

    public static final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptor() {
        return com.bok.bank.integration.grpc.BankProto.getDescriptor().getEnumTypes().get(0);
    }

    public static Currency valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
                    "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
    }

    public final int getNumber() {
        if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalArgumentException(
                    "Can't get the number of an unknown enum value.");
        }
        return value;
    }

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
    getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
    }

    public final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptorForType() {
        return getDescriptor();
    }

    // @@protoc_insertion_point(enum_scope:Currency)
}

