// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank.proto

package com.bok.bank.integration.grpc;

public interface MoneyOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Money)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Currency currency = 1;</code>
     *
     * @return The enum numeric value on the wire for currency.
     */
    int getCurrencyValue();

    /**
     * <code>.Currency currency = 1;</code>
     *
     * @return The currency.
     */
    com.bok.bank.integration.grpc.Currency getCurrency();

    /**
     * <code>double amount = 2;</code>
     *
     * @return The amount.
     */
    double getAmount();
}
