// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank.proto

package com.bok.bank.integration.grpc;

public interface MoneyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Money)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string currency = 1;</code>
   * @return The currency.
   */
  java.lang.String getCurrency();
  /**
   * <code>string currency = 1;</code>
   * @return The bytes for currency.
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();

  /**
   * <code>float amount = 2;</code>
   * @return The amount.
   */
  float getAmount();
}
