package com.bok.bank.exception;

public enum ErrorCode {
    CONFIRMATION_TOKEN_NOT_VALID,
    ACCOUNT_ALREADY_EXISTS,
    ACCOUNT_NOT_FOUND,
    BANK_ACCOUNT_NOT_FOUND,
    BANK_ACCOUNT_ALREADY_EXISTS,
    ACCOUNT_ALREADY_HAVE_A_BANK_ACCOUNT,
    AMOUNT_NOT_AVAILABLE,
    TRANSACTION_TYPE_NOT_VALID
}
